version: "4.29.0"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - ./data/privacypolicies/:/data/privacypolicies  # Mount privacy policies directory from relative path
      - ./data/db:/data/db                             # Generic relative path for MongoDB data persistence
    networks:
      - imp-network

  privacypolicyservice:
    build: ./PrivacyPolicyService  # Path to Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongodb-container:27017/privacy-policy-db
    networks:
      - imp-network

  ppcrawler:
    build: ./ppcrawler # Path to Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      MONGODB_URI: mongodb://mongodb-container:27017/privacy-policy-db
    networks:
      - imp-network
networks:
  imp-network:
    driver: bridge
